'''
This script
- reads in the .txt file generated by "Twitter_Thread_StreamingAPI.py"
- creates a JSON object of all the tweets
- writes out the tweets as a JSON file
'''

import json

tweet_file_name = 'Twitter_Zika_FullDataSet'
tweets_data = '../data/%s.txt' %(tweet_file_name)

tweets_data_full = []
tweets_file = open(tweets_data, "r") # read in the .txt data file

# create a list of each tweet (as a json object)
for line in tweets_file:
    try:
        tweet = json.loads(line)
        tweets_data_full.append(tweet)
    except:
        pass

# create a string "s" of the full dataset, indented by 2 characters for easier readability
s = json.dumps(tweets_data_full, indent=2)

# Write out JSON File:
tweet_file_name_out = 'Twitter_Zika_FullData'
with open('../data/%s.json' %(tweet_file_name_out), 'w') as twitterJSONFile_out:
    twitterJSONFile_out.write(s)

# Write out how many tweets this document contained.
print("This document contains %d tweets.\n" %(len(tweets_data_full)))

# Write out the 1st 30 characters of the string, to confirm proper formatting
print("\nThe first 30 characters of the file are:\n\n".join(s[:30]))

